version: "3"

services:
  postgres:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "simple_bank"
    volumes:
      - pg-data:/var/lib/postgresql/data/
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://root:password@postgres:5432/simple_bank?sslmode=disable
      - USE_GRPC_GATEWAY=true
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

volumes:
  pg-data:
